# SVD

In [1]:
import numpy as np
from matplotlib import pyplot as plt
from scipy import linalg as la

### Problem 1

In [77]:
def p_1(A, tol=0.00001):
    herm = A.conj().T
    eigs, vecs = la.eig(herm @ A) #find eigenvalues and vectors
    
    sigma =  np.sqrt(eigs).real #calc singular values
    place = np.argsort(-sigma) #find places to sort singular values
    sigma =  sigma[place] #sort singular values
    vecs = vecs[place, :]
    r = (sigma > tol).sum()
    sigma_1 = sigma[0:r]
    vecs_1 = vecs[:, 0:r]
    u_1 = A @ vecs_1 / sigma_1
    return u_1, sigma_1, vecs_1.conj().T


In [79]:
A = np.random.random((3, 3))
U, s, Vh = la.svd(A, full_matrices=False)
myu, mys, myV = p_1(A)
print(mys)
print(s)

[1.84427136 0.50732451 0.03538984]
[1.84427136 0.50732451 0.03538984]


### Problem 2

In [4]:
test = np.array([[2], [4], [9]])
np.sqrt(test)

array([[1.41421356],
       [2.        ],
       [3.        ]])

In [45]:
A = np.random.random((2,2))
eigs, vecs = la.eig(A)
#loc=np.argmax(eigs)
#lamb, x = eigs[loc], vecs[:, loc]
c = eigs

In [51]:
c[0:2]

array([ 1.04944183+0.j, -0.44580731+0.j])

In [18]:
b = vecs[(1, 0), :]
b

array([[ 0.65817978,  0.65818877],
       [ 0.7528608 , -0.75285293]])

In [38]:
c = np.array([[2, 3, 4]])
d = c[:,0:2]
d

array([[2, 3]])